name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Auth Service dependencies
        run: |
          cd auth_service
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Auth Service tests
        run: |
          cd auth_service
          PYTHONPATH=.. pytest

      - name: Install Product Service dependencies
        run: |
          cd product_service
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Product Service tests
        run: |
          cd product_service
          PYTHONPATH=.. pytest

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Auth Service Docker image
        run: docker build -t auth-service:latest ./auth_service

      - name: Build Product Service Docker image
        run: docker build -t product-service:latest ./product_service
