name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # ðŸ‘‡ GitHub Secret injected here
    env:
      INTERNAL_API_KEY: ${{ secrets.INTERNAL_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Auth Service dependencies
        run: |
          cd auth_service
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Auth Service tests
        run: |
          cd auth_service
          PYTHONPATH=.. pytest

      - name: Install Product Service dependencies
        run: |
          cd product_service
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Product Service tests
        run: |
          cd product_service
          PYTHONPATH=.. pytest
