      - name: Run Auth Service tests
        run: |
          cd auth_service
          PYTHONPATH=.. pytest

      - name: Run Product Service tests
        run: |
          cd product_service
          PYTHONPATH=.. pytest
